#!/bin/bash

_LCL_VERBOSE_=false
if [ "$1" == "-v" ]; then
	_LCL_VERBOSE_=true
fi

source inc/colors.sh
source inc/check_root.sh

if [ -d /var/www/html/glpi_* ]; then
	echo -e "$BRed""ERROR$CRST: GLPI already installed"; exit 1
fi

apt-get update -y &&\
apt-get full-upgrade -y &&\
apt-get install -y apt-transport-https apache2 mariadb-server \
	php php-{fpm,mysql,mbstring,curl,gd,xml,intl,ldap,apcu,xmlrpc,zip,bz2,bcmath}

apt-get install -y zip unzip curl ipcalc sudo
apt-get install -y yes

# ask for server name and local ip
source inc/ask_sql_infos.sh
source inc/ask_server_infos.sh

# echo "CREATE USER $SQL_USERNAME@localhost IDENTIFIED BY \"$SQL_PASSWORD\";" | mariadb

# set timezone
read -p "Enter timezone: " LOCAL_TIMEZONE
if [ "$LOCAL_TIMEZONE" != "" ] ;then
	timedatectl set-timezone $LOCAL_TIMEZONE
	mariadb-tzinfo-to-sql timezone_dir
fi

# additional default apache config
systemctl stop apache2
a2enmod proxy_fcgi setenvif rewrite
a2enconf php*-fpm
a2dissite 000-default.conf

source inc/fetch_remote_glpi_tag.sh

source inc/setup_glpi_site.sh

cd $GLPI_FOLDER_PATH
yes | sudo -u www-data php bin/console db:install -L fr_FR -d glpi_$GLPI_TAG -u $SQL_USERNAME -p $SQL_PASSWORD

chown -R www-data:www-data /var/www/html

systemctl start apache2

echo ""
echo '_/"\_/"\_/"\_/"\_/"\_/"\_/"\_/"\_/"\_/"\_/'
echo '"\_/"\_/"\_/"\_/"\_/"\_/"\_/"\_/"\_/"\_/"\'
echo "$BGreen      HURAY! Installation is now complete!$CRST"
echo '_/"\_/"\_/"\_/"\_/"\_/"\_/"\_/"\_/"\_/"\_/'
echo '"\_/"\_/"\_/"\_/"\_/"\_/"\_/"\_/"\_/"\_/"\'
