#!/bin/bash

_LCL_VERBOSE_=false
if [ "$1" == "-v" ]; then
	_LCL_VERBOSE_=true
fi

source inc/check_root.sh

# script to list installed version
ALL_VERSION=$(ls -l /etc/apache2/sites-enabled/glpi-* | grep -Eo 'glpi-.*' | sed 's/.conf//g')
LIVE_VERSION=$(cat /etc/apache2/sites-enabled/glpi.conf | grep '# live version' | grep -Eo '([0-9]+\.?)+')

echo "Live version is: $LIVE_VERSION"
echo "GLPI current deployed versions are:"
echo $ALL_VERSION | sed 's/ /\n/g'

