#!/bin/bash

sudo a2dissite '*'
sudo rm -rf /var/www/html/glpi*
sudo rm /etc/apache2/sites-available/*glpi*
echo "DROP DATABASE ""$(echo "SHOW DATABASES LIKE '%glpi%';" | sudo mariadb | grep glpi_ | head -n 1)"";" | sudo mariadb
echo "DROP DATABASE ""$(echo "SHOW DATABASES LIKE '%glpi%';" | sudo mariadb | grep glpi_ | head -n 1)"";" | sudo mariadb
sudo systemctl restart apache2

