#!/bin/bash

source inc/globals/variables.sh
source inc/globals/colors.sh

echo -e "$BRed""WARNING$CRST bypass option forces deletion, press a key to continue"
read -n 1 -s

sudo a2dissite '*'
sudo rm -rf $WWW_DIR/glpi*
sudo rm /etc/apache2/sites-available/*glpi*
echo "DROP DATABASE ""$(echo "SHOW DATABASES LIKE '%glpi%';" | sudo mariadb | grep glpi_ | head -n 1)"";" | sudo mariadb
sudo systemctl restart apache2

