#!/bin/bash

_LCL_VERBOSE_=false
if [ "$1" == "-v" ]; then
	_LCL_VERBOSE_=true
fi

# root check is done in list_glpi_versions
source list_glpi_versions

# fetch the last remote version tag to compare
source inc/fetch_remote_glpi_tag.sh

if [ "$GLPI_VERSION" ==  "$LIVE_VERSION" ]; then
	echo "Current live version si already up to date, exiting..."
	exit 0
fi

HARD_BACKUPS_PATH=/home/www-data-backups
HARD_BACKUPS_FILE=$HARD_BACKUPS_PATH/glpi_$(date +'%d_%m-%H_%M')
mkdir -p $HARD_BACKUPS_PATH
chown -R www-data $HARD_BACKUPS_PATH

OLD_VERSION=$(echo "$ALL_VERSION" | grep -v "$LIVE_VERSION" | sed 's/glpi-//')
if [ "$OLD_VERSION" == "" ]; then
	OLD_VERSION="N/A"
fi
if [ "$_LCL_VERBOSE_" == true ]; then
	echo "Old verion found: $OLD_VERSION"
fi

source inc/ask_sql_infos.sh

systemctl stop apache2

# Backup and remove old version
if [ "$OLD_VERSION" != "N/A" ]; then
	OLD_TAG="$(echo $OLD_VERSION | sed 's/\./_/g')"
	OLD_FOLDER_NAME="glpi_$OLD_TAG"
	OLD_FOLDER_PATH="/var/www/html/$OLD_FOLDER_NAME"
	mysqldump -u $SQL_USERNAME -p$SQL_PASSWORD glpi_$OLD_TAG > /tmp/glpi_$OLD_TAG.sql

	zip -r "$HARD_BACKUPS_FILE"_"$OLD_TAG".zip \
	/etc/apache2/sites-available/glpi-archive.conf \
	/tmp/glpi_$OLD_TAG.sql \
	/var/www/html/glpi_$OLD_TAG/{config,files,marketplace,plugins}/

	chown -R www-data:www-data $HARD_BACKUPS_PATH
	chmod 660 -R $HARD_BACKUPS_PATH

	# clean up
	rm -rf /var/www/html/glpi_$OLD_TAG/
	rm /etc/apache2/sites-available/glpi-archive.conf
	echo "DROP DATABASE glpi_$OLD_TAG;" | mariadb
fi

SERVER_IP=$(cat /etc/apache2/sites-available/001-glpi.conf \
	| grep -Eo 'ServerAlias .*$' \
	| sed 's/ServerAlias //')

# Building archive version configuration
cat rss/apache_archive_conf_template.txt \
| sed "s/_SERVER_NAME_/glpi-archive/g" \
| sed "s/_SERVER_LOCAL_IP_/$SERVER_IP/g" \
| sed "s/_PHP_VERSION_/$CURR_PHP_VER/g" \
| sed "s/_URL_/glpi_archive/g" \
| sed "s/_GLPI_FOLDER_NAME_/$GLPI_FOLDER_NAME/g" \
> /etc/apache2/sites-available/glpi-archive.conf

# Download and setup new site
source inc/setup_glpi_site.sh

GLPI_PPREFIX=/var/www/html/glpi_
# copy files
cp -a $GLPI_PPREFIX$LIVE_TAG/config/* $GLPI_PPREFIX$GLPI_TAG/config/
cp -a $GLPI_PPREFIX$LIVE_TAG/files/* $GLPI_PPREFIX$GLPI_TAG/files/
cp -a $GLPI_PPREFIX$LIVE_TAG/marketplace/* $GLPI_PPREFIX$GLPI_TAG/marketplace/
cp -a $GLPI_PPREFIX$LIVE_TAG/plugins/* $GLPI_PPREFIX$GLPI_TAG/plugins/
chown -R www-data:www-data $GLPI_PPREFIX$GLPI_TAG/*

# import database and change database name
mysqldump -u $SQL_USERNAME -p$SQL_PASSWORD glpi_$LIVE_TAG | sed "s/-- MariaDB dump.*/USE glpi_$GLPI_TAG;/" | mariadb
cd $GLPI_FOLDER_PATH
yes | sudo -u www-data php bin/console db:configure -d glpi_$GLPI_TAG -u $SQL_USERNAME -p $SQL_PASSWORD

systemctl start apache2
